// Keys are only used to request a view. The server owns the role-permission matrix.
export type Permission =
  | 'admin.dashboard.view'
  | 'credit.products.manage'
  | 'investment.products.manage'
  | 'institution.manage'
  | 'users.roles.manage'
  | 'identity.verification.start'
  | 'credit.request.create'
  | 'investment.request.create'
  | 'simulation.save'
  | 'own.requests.read'
  | 'credit.requests.review'
  | 'credit.requests.approve'
  | 'investment.requests.review'
  | 'requests.audit'
